# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='descriptin',
            new_name='description',
        ),
    ]
